services:
  frigate-telegram-bot:
    build: .
    container_name: frigate-telegram-bot
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.yml:/config/config.yml:ro
      - bot-data:/data
    environment:
      - TZ=Europe/Moscow

volumes:
  bot-data:
